baseURL = 'https://example.org/'
languageCode = 'de-de'
title = 'Steinbart MakerSpace'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Neuigkeiten'
pageRef = '/neuigkeiten'
weight = 20

[[menus.main]]
name = 'Über uns'
pageRef = '/ueberuns'
weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
